import streamlit as st
import pandas as pd
import plotly.express as px

# ==================================================
# PAGE CONFIG
# ==================================================

st.set_page_config(
    page_title="Reports Dashboard",
    page_icon="📊",
    layout="wide"
)

# ==================================================
# HEADER
# ==================================================

st.title("📊 Reports Dashboard")
st.caption(
    "Generate and analyse school reports and performance metrics."
)

# ==================================================
# KPI CARDS
# ==================================================

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric(
        "Reports Generated",
        "156",
        "+12"
    )

with col2:
    st.metric(
        "Attendance Rate",
        "90.7%"
    )

with col3:
    st.metric(
        "Communication Reach",
        "94%"
    )

with col4:
    st.metric(
        "Active Learners",
        "1,248"
    )

st.divider()

# ==================================================
# REPORT FILTERS
# ==================================================

col1, col2, col3 = st.columns(3)

with col1:
    report_type = st.selectbox(
        "Report Type",
        [
            "Attendance Report",
            "Learner Report",
            "Communication Report",
            "Admissions Report"
        ]
    )

with col2:
    start_date = st.date_input(
        "Start Date"
    )

with col3:
    end_date = st.date_input(
        "End Date"
    )

st.divider()

# ==================================================
# ATTENDANCE TREND
# ==================================================

left, right = st.columns([2,1])

with left:

    st.subheader("Attendance Performance")

    attendance_df = pd.DataFrame({
        "Month":[
            "Jan",
            "Feb",
            "Mar",
            "Apr",
            "May"
        ],
        "Attendance":[
            88,
            89,
            90,
            92,
            91
        ]
    })

    fig1 = px.line(
        attendance_df,
        x="Month",
        y="Attendance",
        markers=True
    )

    st.plotly_chart(
        fig1,
        use_container_width=True
    )

with right:

    st.subheader("Quick Reports")

    st.button(
        "📋 Attendance Report",
        key="attendance_report"
    )

    st.button(
        "👨‍🎓 Learner Report",
        key="learner_report"
    )

    st.button(
        "📢 Communication Report",
        key="communication_report"
    )

    st.button(
        "📥 Export PDF",
        key="export_pdf"
    )

st.divider()

# ==================================================
# LEARNERS BY GRADE
# ==================================================

left, right = st.columns(2)

with left:

    st.subheader("Learners by Grade")

    learners_df = pd.DataFrame({
        "Grade":[
            "Grade 8",
            "Grade 9",
            "Grade 10",
            "Grade 11",
            "Grade 12"
        ],
        "Learners":[
            250,
            240,
            255,
            248,
            255
        ]
    })

    fig2 = px.bar(
        learners_df,
        x="Grade",
        y="Learners"
    )

    st.plotly_chart(
        fig2,
        use_container_width=True
    )

with right:

    st.subheader("Gender Distribution")

    gender_df = pd.DataFrame({
        "Gender":[
            "Male",
            "Female"
        ],
        "Count":[
            612,
            636
        ]
    })

    fig3 = px.pie(
        gender_df,
        names="Gender",
        values="Count"
    )

    st.plotly_chart(
        fig3,
        use_container_width=True
    )

st.divider()

# ==================================================
# COMMUNICATION ANALYTICS
# ==================================================

st.subheader("Communication Analytics")

comms_df = pd.DataFrame({
    "Month":[
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May"
    ],
    "Messages":[
        180,
        220,
        250,
        270,
        310
    ]
})

fig4 = px.bar(
    comms_df,
    x="Month",
    y="Messages",
    text="Messages"
)

st.plotly_chart(
    fig4,
    use_container_width=True
)

st.divider()

# ==================================================
# REPORT HISTORY
# ==================================================

st.subheader("Recent Reports")

history_df = pd.DataFrame({
    "Report":[
        "Attendance Report",
        "Communication Report",
        "Learner Summary",
        "Admissions Report"
    ],
    "Generated By":[
        "Principal",
        "Administrator",
        "Principal",
        "Administrator"
    ],
    "Date":[
        "2026-05-18",
        "2026-05-19",
        "2026-05-20",
        "2026-05-22"
    ]
})

st.dataframe(
    history_df,
    use_container_width=True,
    hide_index=True
)

st.divider()

st.info(
    "Reports Dashboard - Rentabuka School Management System"
)
